# Generated by Django 3.0.8 on 2020-07-27 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200725_2346'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
